version: '3'

services:
  node-app:
    build: .
    ports:
      - '8000:8000'
    depends_on:
      - mongo
    networks:
      - node-app

  mongo:
    container_name: mongo
    iamge: mongo-alphine
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    networks:
      - node-app

volumes:
  mongo-data:
    name: ${VOLUME_ID}

networks:
  node-app:
    driver: bridge
